cleanup - unable to find cause of NoSuchMethodError: Class Unspent has no instance getter address. Receiver: Instance of Unspent Tried calling: address... without ability to recreate or stacktrace